from application.model.entity.estado import Estado
from application.model.entity.noticia import Noticia

class EstadoDAO:
    def __init__(self):
        noticia1 = Noticia(1,"São Paulo tem semana mais mortal da pandemia, com 5.657 óbitos.",
        'video/noticia1.mp4','img/noticia1.png','O estado de São Paulo teve a semana com mais mortes da pandemia entre 4 e 10 de abril, com 5.657 óbitos. É praticamente o triplo do número de vítimas da semana com mais mortes na primeira onda, em meados de julho, quando 1.945 pessoas perderam a vida devido à covid-19. Os dados são da Secretaria Estadual de Saúde, compilados pelo consórcio de imprensa de que o UOL faz parte. Hoje (11) foram registradas 510 mortes por covid-19 --o número é extremamente alto para um domingo, quando a quantidade de dados incluída no sistema costuma cair. O número de mortes por covid-19 na última semana é 13% maior do que na anterior. Já faz seis semanas que a quantidade de vítimas da pandemia sobe sem para em São Paulo. O número de casos na semana de 4 a 10 de abril também foi o maior já registrado pelo estado. Mas a alta em relação à semana anterior é menor do que a verificada entre as mortes, 5%. Isso é um indicativo de que a pandemia está, muito lentamente, tirando o pé do acelerador --embora ainda esteja acelerando. Os reflexos são sentidos primeiro no número de casos e, só depois, no de mortes --já que, em geral, a covid-19 não provoca morte imediata. Na contramão do número de mortes e casos, a ocupação dos leitos exclusivos para pacientes com covid-19 vem caindo em São Paulo. Depois de passar de 90%, chegou a 86% neste domingo (11).',
        "11/04/2021")

        noticia2 = Noticia(2,"Sem aval da Anvisa para testes, Butantan começa hoje a produzir ButanVac.",'video/noticia2.mp4','img/noticia2.png','  O Instituto Butantan começa hoje a produzir as primeiras doses da ButanVac, a vacina contra a covid-19 que deve ter produção 100% nacional, sem a necessidade da importação de matéria-prima. O instituto, porém, ainda precisa de um aval da Anvisa (Agência Nacional de Vigilância Sanitária) para iniciar os testes clínicos do imunizante em humanos. Ontem, a agência negou a autorização e pediu o complemento de documentação por parte do Butantan, que se comprometeu em atender às exigências. Antes disso, o UOL havia adiantado que o instituto pretendia começar a produção da ButanVac ainda nesta semana. Segundo o diretor do Butantan, Dimas Covas, a instituição começará a produzir inicialmente um primeiro lote com um milhão de doses, mas tem a expectativa de produzir 18 milhões de doses até junho. O anúncio do início da produção vem num momento em que o país enfrenta uma escassez de oferta de doses da CoronaVac, a vacina contra a covid-19 envasada pelo Butantan com insumos importados da China. Há problemas em diversas cidades brasileiras, principalmente, com a aplicação da dose de reforço.Linha de produção da vacina contra a gripe O Butantan alega que a distribuição das doses é de responsabilidade do Ministério da Saúde, que chegou a orientar os municípios a não guardarem a segunda dose e usarem todo o estoque. Durante a coletiva realizada hoje no Instituto Butantan, com a equipe do governador João Doria (PSDB), a coordenadora do programa estadual de imunização, Regiane de Paula, repetiu que não há falta de doses no estado de São Paulo. De acordo com o Butantan, a fabricação da ButanVac vai ocorrer em uma linha de produção que vinha sendo utilizada para a vacina contra a gripe. A CoronaVac é produzida e envasada em outro maquinário. Assim como a vacina da gripe, o Butantan utilizará para a ButanVac a técnica de obtenção do IFA (Insumo Farmacêutico Ativo) a partir do cultivo de cepas do vírus em ovos de galinha. A instituição tem hoje um primeiro lote com 520 mil ovos que receberão o vírus, rendendo depois duas doses da vacina cada um. No anúncio da ButanVac, há cerca de um mês, o governo paulista e o Butantan chegaram a classificar a vacina como "100% brasileira". Logo depois, porém, a instituição admitiu que usou uma tecnologia criada no Hospital Mount Sinai, de Nova York, nos Estados Unidos. A ButanVac é desenvolvida por um consórcio internacional, mas poderá ser produzida integralmente no Butantan, com custo mais baixo.',
        "28/04/2021")

        noticia3 = Noticia(3,"Rio de Janeiro começa a vacinar professores da rede privada nesta segunda",'video/noticia3.mp4','img/noticia3.png', "O Rio de Janeiro começa a vacinar nesta segunda-feira, 26, professores da rede particular. Profissionais com 59, 58 e 57 anos poderão receber o imunizante a partir de hoje. Até então a vacina estava disponível apenas para professores de escolas públicas. O secretário municipal de Educação do Rio, Renan Ferreirinha, explicou que outros profissionais de ensino também poderão ser imunizados. “A vacinação é para todos os profissionais da educação. Professores, merendeiros, secretários, terceirizados, todos. Até porque a educação é feita por todos. Aqui no Rio, educação é prioridade.” Para receber a vacina contra a Covid-19, o profissional deve apresentar um documento com foto e o último contracheque.","26/04/2021")

        noticia4 = Noticia(4,"Covid-19: Rio tem 1,31 mil autuações no terceiro dia de fiscalização.",'video/noticia4.mp4','img/noticia4.png',"No terceiro dia de fiscalização das novas medidas de flexibilização que valem até o dia 19 deste mês, a prefeitura do Rio de Janeiro registrou 1.311 autuações, entre multas e interdições a estabelecimentos, infrações sanitárias, multas de trânsito, reboques e apreensões de mercadorias. Entre o domingo (11) e a madrugada desta segunda-feira (12), foram aplicadas 97 multas a bares, restaurantes e ambulantes e nove estabelecimentos foram interditados.Desde sexta-feira (9), as equipes de fiscalização já registraram 3.907 autuações, com 202 multas aplicadas a bares, restaurantes e vendedores ambulantes e 74 estabelecimentos e festas fechados.","12/04/2021")

        estado1 = Estado("São Paulo","SP",'img/saopaulo.png',[noticia1,noticia2])
        estado2 = Estado("Rio de Janeiro","RJ",'img/riodejaneiro.png',[noticia3,noticia4])
        self.__estados = [estado1,estado2]